### ISSUE TITLE
Clicked number are not showing in the input bar instead "${inputfield.value}${event.target.innerHTML} " is showing..

### ISSUE THREAD

**Issue by SayedAmmar7** [SayedAmmar7/Calculator#1]
I think there is a problem in line number 22 of index.js file.

" default:
                    inputtext= '${inputfield.value}${event.target.innerHTML}'; "

**Comment by shmarsy** [comment]
I want to resolve this issue.

**Comment by SayedAmmar7** [comment]
default:
                    inputtext= `${inputfield.value}${event.target.innerHTML}`;

**Comment by SayedAmmar7** [comment]
Isuue #1 fixed
